version: '3.0'

services:
  mysql:
    container_name: codelytv-netcore_ddd_skeleton-mooc-mysql
    image: mysql:8
    ports:
      - "3360:3306"
    environment:
      - MYSQL_DATABASE=netcore-ddd-skeleton
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: ["--default-authentication-plugin=mysql_native_password"]